on:
  push:
    branches:
      - main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # - name: Check NPM Registry
      #   run: npm config get registry

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Dependencies
        run: |
          sudo Rscript -e 'install.packages("drat", repos="https://cloud.r-project.org")'
          # sudo apt-get update
          # sudo apt-get install -y nodejs
          # npm install -g quarto
          # npm install -g quarto-render-html

      - name: Build Table
        run: quarto render table/table.qmd

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          branch: gh-pages
          # target: gh-pages
          folder: .
          clean: true
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}